#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "engine.h"
#include "cfg.c"
#include "optimizations/algebraic_simplification.c"
#include "optimizations/common_subexpression_elimination.c"
#include "optimizations/constant_folding.c"
#include "optimizations/constant_propagation.c"
#include "optimizations/copy_propagation.c"
#include "optimizations/dead_code_elimination.c"
#include "optimizations/function_cloning.c"
#include "optimizations/function_inlining.c"
#include "optimizations/induction_variable_elimination.c"
#include "optimizations/loop_fusion.c"
#include "optimizations/loop_invariant_code_motion.c"
#include "optimizations/loop_peeling.c"
#include "optimizations/loop_unrolling.c"
#include "optimizations/strength_reduction.c"
#include "optimizations/unreachable_code_elimination.c"
#include "parser.c"

void run_pipeline(FunctionIR *ir) {
    int changed = 1;
    int iterations = 0;
    const int max_iterations = 20;

    while (changed && iterations < max_iterations) {
        changed = 0;
        changed |= algebraic_simplification(ir);
        changed |= constant_propagation(ir);
        changed |= copy_propagation(ir);
        changed |= constant_folding(ir);
        changed |= common_subexpression_elimination(ir);
        changed |= strength_reduction(ir);
        changed |= function_inlining(ir);
        changed |= function_cloning(ir);
        changed |= loop_invariant_code_motion(ir);
        changed |= induction_variable_elimination(ir);
        changed |= loop_fusion(ir);
        changed |= loop_peeling(ir);
        changed |= loop_unrolling(ir);
        changed |= dead_code_elimination(ir);
        iterations++;
    }
    printf("Optimization completed in %d iterations.\n", iterations);
}

void print_optimized_gimple(FunctionIR ir) {
    int printed = 0;
    for (int i = 0; i < ir.count; i++) {
        GimpleInst *ins = &ir.insts[i];
        if (ins->is_dead) continue; // Skip dead instructions

        switch (ins->type) {
            case G_GOTO:
                printf("goto %s;\n", ins->dest);
                printed++;
                break;
            case G_LABEL:
                printf("%s:\n", ins->dest);
                printed++;
                break;
            case G_COND:
                printf("if (%s %s %s) goto %s;\n", ins->arg1, ins->op, ins->arg2, ins->dest);
                printed++;
                break;
            case G_CALL:
                if (strlen(ins->dest) > 0)
                    printf("%s = call %s;\n", ins->dest, ins->arg1);
                else
                    printf("call %s;\n", ins->arg1);
                printed++;
                break;
            case G_ASSIGN:
                if (strlen(ins->op) > 0)
                    printf("%s = %s %s %s;\n", ins->dest, ins->arg1, ins->op, ins->arg2);
                else
                    printf("%s = %s;\n", ins->dest, ins->arg1);
                printed++;
                break;
            // Handle other instruction types as needed
            default:
                break;
        }
    }
    fprintf(stderr, "Printed %d non-dead instructions\n", printed);
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <source-file>\n", argv[0]);
        return 1;
    }

    const char *source_file = argv[1];

    // 1. Invoke GCC to dump raw GIMPLE
    const char *gimple_file = "/tmp/compiler_dump.gimple";
    char cmd[768];
    snprintf(cmd, sizeof(cmd), "gcc -fdump-tree-gimple-raw=%s %s -o /tmp/compiler_input.out", gimple_file, source_file);
    if (system(cmd) != 0) {
        fprintf(stderr, "Failed to generate GIMPLE dump for %s\n", source_file);
        return 1;
    }

    // 2. Parse the .gimple file generated by GCC
    FunctionIR ir = parse_gimple_file(gimple_file);
    fprintf(stderr, "Parsed %d instructions from GIMPLE\n", ir.count);
    printf("Original GIMPLE:\n");
    print_optimized_gimple(ir); // Print before optimization for debugging

    // 3. Run the optimization logic
    run_pipeline(&ir);

    // 4. Output optimized GIMPLE
    printf("\nOptimized GIMPLE:\n");
    print_optimized_gimple(ir);

    return 0;
}